### PR TITLE
Gothic Dark theme

### PR DESCRIPTION
**Pull request by gilbertohasnofb**

### CODE REVIEW

**Comment by abnerlee** [comment]
Could you add this as a fork following https://github.com/typora/typora-theme-gallery/pull/74/files? And change from `category: theme` to `category: fork`?

**Comment by gilbertohasnofb** [comment]
@abnerlee Sure, just two questions:

* the example you send me is located in `/_posts/fork/`, but the YAML header still has `category` set to `theme`; should that be changed to `fork` too?
* how do users download those themes located in `/_posts/fork/`? I don't seem to see any of them in http://theme.typora.io/

**Comment by abnerlee** [comment]
> he example you send me is located in /_posts/fork/, but the YAML header still has category set to theme; should that be changed to fork too?

Yes.

> how do users download those themes located in /_posts/fork/? I don't seem to see any of them in http://theme.typora.io/

For now, please also edit the md post file for original theme to add the description / image / link for your forked theme.
In future, we will add some badge or shortcut in home page as well to indicate a theme as alternatives/forks.

**Comment by gilbertohasnofb** [comment]
@abnerlee Ok, no problems.

> For now, please also edit the md post file for original theme to add the description / image / link for your forked theme.

This is fine for my fork of the Gothic theme, but the Whitey theme does not have a page in this repo so I am not sure what to do with my other PR https://github.com/typora/typora-theme-gallery/pull/166

Would you like me to create an entry for the Whitey theme and mention that it is a built-in theme, similarly to the Gothic theme page?

edit: this should be ready to be merged, but please let me know what to do with my Whitey Dark theme in the other PR

**Comment by abnerlee** [comment]
> Would you like me to create an entry for the Whitey theme and mention that it is a built-in theme, similarly to the Gothic theme page?

Sure, thank you very much!

**Pull request merged**
