### PR TITLE
Updated Nord theme to v1.2

### PR DESCRIPTION
**Pull request by ChristosBouronikos**

### CODE REVIEW

**Comment by ChristosBouronikos** [comment]
@abnerlee although the pull request was merged, Nord theme doesn't show up on [the website](theme.typora.io).
On the contrary the fluent theme that was merged after mine is up on the theme gallery.
Did I do anything wrong on my part?

**Comment by abnerlee** [comment]
```
\---

layout: theme

title: Nord

category: theme

homepage: [https://github.com/ChristosBouronikos/typora-nord-theme/](https://github.com/ChristosBouronikos/typora-nord-theme/)

download: [https://github.com/ChristosBouronikos/typora-nord-theme/releases/download/v1.2](https://github.com/ChristosBouronikos/typora-nord-theme/releases/download/v1.2/TyporaNordTheme-by-ChristosBouronikos.zip)

built-in: false

author: Christos Bouronikos

thumbnail: nord.png

typora-root-url: ../../

typora-copy-images-to: ../../media/theme/nord



\---
```

should be 

```
---
layout: theme
title: Nord
category: theme
homepage: [https://github.com/ChristosBouronikos/typora-nord-theme/](https://github.com/ChristosBouronikos/typora-nord-theme/)
download: [https://github.com/ChristosBouronikos/typora-nord-theme/releases/download/v1.2](https://github.com/ChristosBouronikos/typora-nord-theme/releases/download/v1.2/TyporaNordTheme-by-ChristosBouronikos.zip)
built-in: false
author: Christos Bouronikos
thumbnail: nord.png
typora-root-url: ../../
typora-copy-images-to: ../../media/theme/nord
---
```

**Comment by abnerlee** [comment]
I fixed in https://github.com/typora/typora-theme-gallery/commit/2769abc2d8c473a4bc3b2ff94dcfe3a1e79f0cac

**Comment by ChristosBouronikos** [comment]
Thanks so much and sorry for putting you in so much trouble.

**Pull request merged**
