### PR TITLE
Adding my theme, Premito

### PR DESCRIPTION
**Pull request by gatlinnewhouse**
Let me know if there is anything I need to do!

### CODE REVIEW

**Comment by gatlinnewhouse** [comment]
Hold up, lemme push some updates later.

**Comment by abnerlee** [comment]
@gatlinnewhouse Thanks, some changes should be our bug fix.

I added something on the document "Submit a Theme":

> If only small modifications are introduced, like changing a font or changing the padding of write area based on an existing theme, we could recommend you to edit the post of the original theme, and add links or descriptions about your “forked” one.

So, I'm thinking that I will post a doc about the default theme -- "Github", and you add descriptions about your theme as a related forked one on that post, what do you think?

**Comment by gatlinnewhouse** [comment]
Okay sick! I can submit that with the next commit!

**Comment by abnerlee** [comment]
@gatlinnewhouse sorry for getting back you late, I cherry-picked your commit and make a new rule/example for submitting forked theme like Premito at https://github.com/typora/typora-theme-gallery/pull/12

Please check if that is OK for you ~

**Pull request closed without merging**
