### PR TITLE
Premito

### PR DESCRIPTION
**Pull request by abnerlee**

### CODE REVIEW

**Comment by gatlinnewhouse** [comment]
Yeah, although I need to push a quick update to the `.css` and `.zip` for mostly printing options. I'll submit a pull request for that.

**Comment by gatlinnewhouse** [comment]
Unless my commit will come here?

**Comment by gatlinnewhouse** [comment]
I opened #13 to merge the final version of Premito into the premito branch.

**Comment by abnerlee** [comment]
:+1:

**Pull request merged**
