### PR TITLE
Updated version with LIGHT and DARK theme.

### PR DESCRIPTION
**Pull request by bauhausblack**

### CODE REVIEW

**Comment by abnerlee** [comment]
@pink-bird Hi, thanks. 
I would personally recommend to remove the screen frame in the `media/thumbnails/minimalism.png` , since the thumbnail is a very small image and should be more focused on the theme itself.

What do you think?

**Comment by bauhausblack** [comment]
@abnerlee Did I get you right, you mean to remove the notebook frame, for just seeing the "on-screen-picture" from theme? Would be no problem at all...

_Gesendet von meinem Sony F5121 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abnerlee** [comment]
@pink-bird Yes, that is what I mean. Thanks!

**Comment by bauhausblack** [comment]
Allright, found some time for the updated thumbnail picture...

**Pull request merged**
