### PR TITLE
update scrolls

### PR DESCRIPTION
**Pull request by daodaolee**
add scrolls darkMode

### CODE REVIEW

**Comment by abnerlee** [comment]
Hmm... Why delete so many other files?

**Comment by daodaolee** [comment]
I didn't mean to, I synchronized the fork project, then submitted it, and then prompted to delete so many files, so should I fork again?😩😩

**Comment by daodaolee** [comment]
> Hmm... Why delete so many other files?

I didn't mean to, I synchronized the fork project, then submitted it, and then prompted to delete so many files, so should I fork again?😩

**Comment by abnerlee** [comment]
The easiest way may be to for again.

**Comment by daodaolee** [comment]
> The easiest way may be to for again.

ok！I'll do it right away

**Pull request closed without merging**
